version: '3.9'
services:
  fetcher:
    build: .
    command: gosu user python3 main.py --schedule
    restart: always
    volumes:
      - "${HOST_DATA_DIR:-./data}:/work/data"

  web:
    image: nginx:1.21
    restart: always
    ports:
      - "${NGINX_PORT:-127.0.0.1:8000}:80"
    volumes:
      - "./default.nginx:/etc/nginx/conf.d/default.conf"
      - "${HOST_DATA_DIR:-./data}:/var/www/html/data"
