version: '3.9'
services:
  fetcher:
    build: .
    command: python3 main.py --schedule
    restart: always
    volumes:
      - "${HOST_DATA_DIR}:/work/data"

  web:
    image: nginx:1.21
    restart: always
    ports:
      - "${NGINX_PORT:-127.0.0.1:8000}:80"
    volumes:
      - "./default.nginx:/etc/nginx/conf.d/default.conf"
      - "${HOST_DATA_DIR}:/var/www/html/data"
